Used cntrl-] to shift over elements to be inside code blocks
rh-mobb/documentation pull request #134
Opened 2022-03-28 21:58 UTC by supernovae

cleaned up code blocks that dropped out of their blocks

2022-03-28 22:06 UTC, supernovae commented
Alright, i think it's formatted. Please squash when merged. Thanks :)

2022-03-28 22:51 UTC, datianshi approved these changes

2022-03-28 22:53 UTC, datianshi approved these changes

2022-03-29 13:54 UTC, datianshi approved these changes

2022-03-29 14:49 UTC, paulczar requested changes
no, the code blocks are left shifted specficailly to solve a weird jekyll formatting issue

2022-03-29 15:26 UTC, closed without merging