added cost management documentation
rh-mobb/documentation pull request #208
Opened 2022-08-29 19:35 UTC by FungCharlotte

2022-08-29 19:52 UTC, cwooley-rh commented
Would we want to segment out the Azure Cost mgmt best practices from AWS?

2022-08-29 20:19 UTC, FungCharlotte commented
@cwooley-rh , you are right. I'll take out that section, and then do another documentation on how to add AWS cloud source to cost management. Thanks

2022-08-29 21:33 UTC, cwooley-rh approved these changes

2022-09-01 18:01 UTC, paulczar requested changes

2022-09-01 18:01 UTC, paulczar commented on docs/cost-management/README.md
> +> See the following video for a quick overview of Cost Management for OpenShift followed by a demo of the product
this should be indented three times `   > See the ....`  in order to be inside the ordered list.

2022-09-01 18:01 UTC, paulczar commented on docs/cost-management/README.md
> +After adding your Openshift Container Platform and Cloud Provider sources, Cost management will show cost data by
a space between this and the ordered list.

2022-09-05 22:24 UTC, merged