Update public-ingress.md to add a blog link which details about arc…
rh-mobb/documentation pull request #371
Opened 2023-06-26 08:15 UTC by sureshgaikwad

…hitecture of ROSA behind AWS NF & WAF

Add the blog link which details the steps and architecture to deploy ROSA in a truly private VPC. Additionally, the blog details about creating CloudFront distribution for content delivery and WAF to protect web applications by filtering and monitoring HTTP traffic between a web application and the internet. Also, the AWS network firewall will be used for fine-grained control over network traffic.

2023-06-26 11:02 UTC, Conan-Kudo requested changes

2023-06-26 11:02 UTC, Conan-Kudo commented on content/docs/rosa/private-link/public-ingress.md
> +Refer to the blog ["How to add public Ingress to a PrivateLink ROSA cluster"](https://developers.redhat.com/articles/2023/04/27/how-add-public-ingress-private-link-rosa-cluster#), to expose applicati
Drop that trailing `#` in the URL.

2023-06-26 12:53 UTC, sureshgaikwad commented on content/docs/rosa/private-link/public-ingress.md
> +Refer to the blog ["How to add public Ingress to a PrivateLink ROSA cluster"](https://developers.redhat.com/articles/2023/04/27/how-add-public-ingress-private-link-rosa-cluster#), to expose applicati
Done

2023-06-27 04:48 UTC, Conan-Kudo approved these changes

2023-06-27 04:49 UTC, merged