Adding a complete how to of LokiStack on ROSA
rh-mobb/documentation pull request #546
Opened 2024-07-05 11:23 UTC by andyrepton

2024-07-05 14:24 UTC, paulczar requested changes

2024-07-05 14:24 UTC, paulczar commented on content/o11y/openshift-logging-lokistack/index.md
> +Create environment variables to use later in this process by running the following commands:
1.

2024-07-05 14:24 UTC, paulczar commented on content/o11y/openshift-logging-lokistack/index.md
> +$ export REGION=$(oc get infrastructure cluster -o=jsonpath="{.status.platformStatus.aws.region}")
all of these code blocks need to be indented, or they break the ordered list and it goes back to 1.

2024-07-05 15:45 UTC, bhardesty reviewed
This looks good, and the procedures/steps flow well. I didn't necessarily review for style, but I did note a few small things that I think might improve the readability/flow.

2024-07-05 15:45 UTC, bhardesty commented on content/o11y/openshift-logging-lokistack/index.md
> +A guide to shipping logs and metrics on OpenShift using the new LokiStack setup
Is the purpose of this obvious to users? If not, you might add a bit more here to explain why someone would/should do this.

2024-07-05 15:45 UTC, bhardesty commented on content/o11y/openshift-logging-lokistack/index.md
> +## For ROSA
I think the other Cloud Experts tutorials name this section "Setting up your environment", so I'd suggest that here as well.

2024-07-05 15:45 UTC, bhardesty commented on content/o11y/openshift-logging-lokistack/index.md
> +### If you are using OpenShift 4.14 or higher on AWS (ROSA)
```suggestion
### Create the LokiStack installation (OpenShift 4.14 or higher on AWS (ROSA))
```

2024-07-05 15:45 UTC, bhardesty commented on content/o11y/openshift-logging-lokistack/index.md
> +### If you are using OpenShift 4.13 or lower on AWS (ROSA), or are using a Non-STS cluster
```suggestion
### Create the LokiStack installation (OpenShift 4.13 or lower on AWS (ROSA) and non-STS clusters)
```

2024-07-05 15:45 UTC, bhardesty commented on content/o11y/openshift-logging-lokistack/index.md
> +1. At this point OpenShift logging is installed and configured and is ready to receive logs.
```suggestion
At this point OpenShift logging is installed and configured and is ready to receive logs.
```

2024-07-09 19:37 UTC, paulczar approved these changes

2024-07-09 19:37 UTC, merged